---
title: "Atlanta R Users Group:Animated Charts in R"
author: "Sri Sitharaman"
date: "6/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Example 1

```{r}
library(ggplot2)
library(gganimate)
library(gapminder)
# For each of 142 countries, the package provides values for life  expectancy, GDP per capita,
# and population, every five years, from 1952 to 2007.
head(gapminder)     
# Static plot
p <- ggplot(
  gapminder, 
  aes(x = gdpPercap, y=lifeExp, size = pop, colour = country)) +
  geom_point(show.legend = FALSE, alpha = 0.7) +
  scale_color_viridis_d() +facet_wrap(~continent)+
  scale_size(range = c(2, 12)) +
  scale_x_log10() +labs(x = "GDP per capita", y = "Life expectancy")
p
# transition
p+ transition_time(year) + ease_aes('linear')+
  labs(title = "Year: {frame_time}")

# Save animation
anim_save("gapminder_animation.gif")
```

# Example 2

```{r}
# HSGPA vs. Grad GPA Data
# Dummy data on High School GPA and University graduating student 
# overall GPA by Gender
library(ggplot2)
library(gganimate)
gpa <- read.csv("Gradgender.csv")
str(gpa)
gpa<- na.omit(gpa)
# Static plot
p <- ggplot(
  gpa, 
  aes(x = HSGPA, y=GPA,colour = Gender))+ ggtitle("HSGPA VS. GPA by Gender")+
  geom_point()+scale_x_continuous(breaks = c(2016:2020))+  xlab(NULL) + ylab(NULL)+theme(legend.position="none")+
  theme(text = element_text(size = 15))+ facet_wrap(~Gender)
p
# Transition
p + transition_time(Year) + ease_aes('linear')+
  labs(title = "Year: {frame_time}")

# Save animation
anim_save("hsgpa_gpa_animation.gif")
```

# Example 3

```{r}
# Retention & Graduation Rates
# Ten year trend of University Retention and Graduation Rates
library(ggplot2)
library(gganimate)
library(directlabels)

rg <- read.csv("RGanim2.csv")
str(rg)
head(rg)

# Static plot
g <-ggplot(rg,aes(x=Year, y=value,col=variable, group = variable)) +geom_line(size=1)+ geom_point()+
  xlab(NULL) + ylab(NULL) +  scale_color_manual(values=c("black","firebrick")) +ggtitle("Retention & Graduation Rate")+
  geom_dl(aes(label = variable), method = list(dl.trans(x = x + 0.2), "last.points", cex = 1.0)) +
  theme(legend.position="none")+ scale_x_continuous(breaks = c(2010:2020))+ theme(text = element_text(size = 15))
g

# Transition
g+  transition_reveal(Year) + ease_aes('cubic-in-out')

# Save animation
anim_save("retgradrates_animation.gif")
```
